export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_USER_DETAILS = "ADD_USER_DETAILS";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

export const ADD_USER_PROFILE_IMAGE = "ADD_USER_PROFILE_IMAGE";
export const REMOVE_USER_PROFILE_IMAGE = "REMOVE_USER_PROFILE_IMAGE";
